name: Auto News Fetch

on:
  schedule:
    - cron: "0 * * * *"   # har 1 hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run news fetch script
        run: node src/app/api/news_fetch.js
